// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dm_model_estimator
Rcpp::List dm_model_estimator(IntegerMatrix Y, IntegerVector z, int iter, IntegerMatrix S, bool aggregate, bool store);
RcppExport SEXP _BayesSLAM_dm_model_estimator(SEXP YSEXP, SEXP zSEXP, SEXP iterSEXP, SEXP SSEXP, SEXP aggregateSEXP, SEXP storeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type S(SSEXP);
    Rcpp::traits::input_parameter< bool >::type aggregate(aggregateSEXP);
    Rcpp::traits::input_parameter< bool >::type store(storeSEXP);
    rcpp_result_gen = Rcpp::wrap(dm_model_estimator(Y, z, iter, S, aggregate, store));
    return rcpp_result_gen;
END_RCPP
}
// zinb_model_estimator
Rcpp::List zinb_model_estimator(IntegerMatrix Y, IntegerVector z, NumericVector s, int iter, bool DPP, IntegerMatrix S, bool aggregate, bool store, double b, double h);
RcppExport SEXP _BayesSLAM_zinb_model_estimator(SEXP YSEXP, SEXP zSEXP, SEXP sSEXP, SEXP iterSEXP, SEXP DPPSEXP, SEXP SSEXP, SEXP aggregateSEXP, SEXP storeSEXP, SEXP bSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< bool >::type DPP(DPPSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type S(SSEXP);
    Rcpp::traits::input_parameter< bool >::type aggregate(aggregateSEXP);
    Rcpp::traits::input_parameter< bool >::type store(storeSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(zinb_model_estimator(Y, z, s, iter, DPP, S, aggregate, store, b, h));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesSLAM_dm_model_estimator", (DL_FUNC) &_BayesSLAM_dm_model_estimator, 6},
    {"_BayesSLAM_zinb_model_estimator", (DL_FUNC) &_BayesSLAM_zinb_model_estimator, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesSLAM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
