# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' DM model
#' 
#' @param Y count matrix (taxa by sample)
#' @param z phenotype vector
#' @param iter number of iterations
#' @param S a matrix used to aggregate upper taxonomy classes
#' @param aggregate whether to perform analysis on upper taxonomy classes
#' @param store whether to store additional Bayesian statistics in addition to PPI (posterior probability of inclusion)
#' 
#' @export
dm_model_estimator <- function(Y, z, iter, S, aggregate, store) {
    .Call('_BayesSLAM_dm_model_estimator', PACKAGE = 'BayesSLAM', Y, z, iter, S, aggregate, store)
}

#' ZINB model
#' 
#' @param Y count matrix (taxa by sample)
#' @param z phenotype vector
#' @param iter number of iterations
#' @param S a matrix used to aggregate upper taxonomy classes
#' @param aggregate whether to perform analysis on upper taxonomy classes
#' @param store whether to store additional Bayesian statistics in addition to PPI (posterior probability of inclusion)
#' @param b a hyper parameter
#' @parma h a hyper parameter
#'
#' @export
zinb_model_estimator <- function(Y, z, s, iter, DPP, S, aggregate, store, b, h) {
    .Call('_BayesSLAM_zinb_model_estimator', PACKAGE = 'BayesSLAM', Y, z, s, iter, DPP, S, aggregate, store, b, h)
}

