# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dm_model_estimator <- function(Y, z, iter, S, aggregate, fold_change, b, b_0) {
    .Call(`_mbTest_dm_model_estimator`, Y, z, iter, S, aggregate, fold_change, b, b_0)
}

zinb_model_estimator <- function(Y, z, s, iter, DPP, c_s, S, aggregate, fold_change, b, b_0) {
    .Call(`_mbTest_zinb_model_estimator`, Y, z, s, iter, DPP, c_s, S, aggregate, fold_change, b, b_0)
}

